### PR TITLE
AWS CI etc

### PR DESCRIPTION
**Pull request by laughedelic**
@laughedelic could you please add the text for this? What we talked about in gitter

### CODE REVIEW

**Comment by eparejatobes** [comment]
@laughedelic up up

**Comment by laughedelic** [comment]
Oh, sorry "_ I'll do it after lunch. Where in gitter did we talk about it?

**Comment by eparejatobes** [comment]
in the gsoc15 channel I think

**Comment by laughedelic** [comment]
Hey @eparejatobes in the end I found current text quite complete. I don't know what else to add here... "_

**Pull request merged**
